config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  mount Attachinary::Engine => "/attachinary"

  resources :hotels do
    member do
      get "vote"
    end
  end
  resources :lotions do
    member do
      get "vote"
    end
  end

  resources :users

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'lotions#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/views/elements/_navbar.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  -#Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => "#navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar

    = link_to image_tag("logo.png", style: "height: 85%"), defined?(root_path) ? root_path : "#", class: "navbar-brand", style: "padding: 0; padding-top: 3px;"
    =# link_to "Hotel Lotion Database!", defined?(root_path) ? root_path : "#", class: "navbar-brand", style: "padding: 0; padding-top: 3px;"
  -# Collect the nav links, forms, and other content for toggling
  #navbar-collapse-1.collapse.navbar-collapse
    - if Tag.any?
      %ul.nav.navbar-nav
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Categories
            %b.caret
          %ul.dropdown-menu
            - tags = Tag.order("taggings_count desc").limit(15).sort_by(&:name)
            - tags.each do |tag|
              - if tag.hotels.present?
                %li= link_to tag.name, "/tags/#{tag.dehumanized_name}"
    %ul.nav.navbar-nav.navbar-right
      %li= link_to "View Hotels", hotels_path
      %li= link_to "View Lotions", lotions_path
      - if defined?(Devise)
        - if user_signed_in?
          - if current_user.superuser?
            %li= link_to "Add New User", new_user_path
          - if current_user.admin?
            %li= link_to "Add New Hotel", new_hotel_path
            %li= link_to "Add New Lotion", new_lotion_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              = current_user.email
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Edit Account", edit_user_registration_path
              %li.divider
              %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Login", new_user_session_path
          %li= link_to "Sign Up", new_user_registration_path