config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  mount Attachinary::Engine => "/attachinary"

  resources :hotels do
    member do
      get "vote"
    end
  end
  resources :lotions do
    member do
      get "vote"
    end
  end

  resources :users

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'lotions#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  ratyrate_rater
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items, as: :created_by, foreign_key: :created_by_id, dependent: :nullify
  belongs_to :created_by, :class_name => "User"

  before_save :set_admin_to_true

  def set_admin_to_true
    self.admin = true
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :redirect_unless_superuser, only: [:new, :create, :edit, :update, :destroy, :get_image_list, :get_listings]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :vote]

  # GET /users
  # GET /users.json
  def index
    # TODO: replace sort_order with acts_as_votable
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.created_by = current_user

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    redirect_to hotels_path
    # respond_to do |format|
    #   if @user.update(user_params)
    #     format.html { redirect_to @user, notice: 'User was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @user }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    redirect_to hotels_path
    # @user.destroy
    # respond_to do |format|
    #   format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end


  private ##################################################################################################################################

  # TODO: use declarative_authorization gem when roles/CRUD gets more complex
  def redirect_unless_superuser
    redirect_to root_path unless current_user && current_user.superuser?
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :admin, :superuser)
    end
end

app/views/users/_form.html.haml
- if @user.errors.present?
  = @user.errors.full_messages.join("<br />").html_safe
= form_for @user, :html => { :class => 'form-horizontal form-model' } do |f|
  .form-group
    = f.label :email, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :email, :class => 'text-field form-control', autocomplete: "off"
  .form-group
    = f.label :password, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :password, :class => 'text-field form-control', autocomplete: "off"
  .form-group
    = f.label :admin, :class => 'control-label col-md-2'
    .col-md-10
      = f.check_box :admin, :class => 'text-field form-control', autocomplete: "off"
  .form-group
    = f.label :superuser, :class => 'control-label col-md-2'
    .col-md-10
      = f.check_box :superuser, :class => 'text-field form-control', autocomplete: "off"
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        users_path, :class => 'btn btn-default'                      |

app/views/users/index.html.haml
-# http://www.responsivewebmobile.com/posts/view/2013/06/04/5/Responsive_Pin_Page_templates_free

- model_class = User

#users
  - @users.each do |user|
    .user.masonry-brick
      %h5.text-center
        - truncated_name = truncate(user.name, length: 40, omission: "", separator: " ")
        = link_to(truncated_name, user_url(user))
      .picture
        %a.image{:href => user_url(user), :title => "Title"}
          %img{:alt => "", :src => user.logo_url}/
        .user-content
          .description
            %p=""
          .meta
            %span.price
              -#%i.icon-calendar
              =# money_format(user.price)
            %span
              -#%i.icon-user
              -#%a.btn.btn-green-with-white{href: user.affiliate_url, style: "float: right;", target: "_blank"} View Lotions
            -#%span
            -#  %i.icon-heart-empty
            -#  10
          - if current_user.present? && (current_user.admin? || user.created_by == current_user || current_user.superuser?)
            .meta
              %span
                - if current_user.admin?
                  = link_to "Info", user_path(user)#, {:class => "btn btn-default"}
                - if (user.created_by == current_user) || current_user.superuser?
                  = link_to "Edit", edit_user_path(user)#, {:class => "btn btn-primary"}
                  = link_to t('.destroy', :default => t("helpers.links.destroy")),
                        user_path(user),
                        :method => 'delete',
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }

:javascript
  var $container = $('#users');
      $container.imagesLoaded(function(){
      $container.masonry({
        userSelector : '.user',
        columnWidth : 290,
        isAnimated: true
      });
    });

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Add New %{model}'], :model => User
= render :partial => 'form'

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1
    User Info
.fieldset
  %dl
    %dt.label.label-default= model_class.human_attribute_name(:email)
    %dd
      %pre.prettyprint= @user.email
.form-group
  = link_to t('.back', :default => t("helpers.links.back")), |
    users_path, :class => 'btn btn-success'                  |
  - if user_signed_in? && (current_user == @user.created_by || current_user.superuser?)
    = link_to t('.edit', :default => t("helpers.links.edit")), |
      edit_user_path(@user), :class => 'btn btn-primary'       |
    -#
    = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
      user_path(@user),                                                                                            |
      :method => 'delete',                                                                                         |
      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
      :class => 'btn btn-danger'                                                                                   |