config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  mount Attachinary::Engine => "/attachinary"

  resources :hotels do
    member do
      get "vote"
    end
  end
  resources :lotions do
    member do
      get "vote"
    end
  end

  resources :users

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'lotions#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/lotion.rb
class Lotion < ActiveRecord::Base
  # http://www.sitepoint.com/ratyrate-add-rating-rails-app/
  has_and_belongs_to_many :hotels
  validates_presence_of :name, :image1

  has_attachments :photos, maximum: 10

  belongs_to :created_by, :class_name => "User"

  ratyrate_rateable 'bottle_design', 'overall'

  has_attached_file :image1, :styles => { :tiny => "100x100>", :small => "150x150>", :medium => "400x300>", :large => "800x600>"}
  # validates_attachment :image1, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment_content_type :image1, :content_type => /image/

  has_attached_file :image2, :styles => { :tiny => "100x100>", :small => "150x150>", :medium => "400x300>", :large => "800x600>"}
  # validates_attachment :image2, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment_content_type :image2, :content_type => /image/
end

app/controllers/lotions_controller.rb
class LotionsController < ApplicationController
  before_filter :redirect_unless_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_lotion, only: [:show, :edit, :update, :destroy, :vote]

  # GET /lotions
  # GET /lotions.json
  def index
    # TODO: replace sort_order with acts_as_votable
    @lotions = Lotion.all.order("created_at desc")

    respond_to do |format|
      format.html
      format.json { render json: @lotions }
    end

  end

  # GET /lotions/1
  # GET /lotions/1.json
  def show
  end

  # GET /lotions/new
  def new
    @lotion = Lotion.new
  end

  # GET /lotions/1/edit
  def edit
  end

  # POST /lotions
  # POST /lotions.json
  def create
    @lotion = Lotion.new(lotion_params)
    @lotion.created_by = current_user

    respond_to do |format|
      if @lotion.save
        format.html { redirect_to @lotion, notice: 'Lotion was successfully created.' }
        format.json { render :show, status: :created, location: @lotion }
      else
        format.html { render :new }
        format.json { render json: @lotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lotions/1
  # PATCH/PUT /lotions/1.json
  def update
    respond_to do |format|
      if @lotion.update(lotion_params)
        format.html { redirect_to @lotion, notice: 'Lotion was successfully updated.' }
        format.json { render :show, status: :ok, location: @lotion }
      else
        format.html { render :edit }
        format.json { render json: @lotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lotions/1
  # DELETE /lotions/1.json
  def destroy
    @lotion.destroy
    respond_to do |format|
      format.html { redirect_to lotions_url, notice: 'Lotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @lotion.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end

  private ##################################################################################################################################

  # TODO: use declarative_authorization gem when roles/CRUD gets more complex
  def redirect_unless_admin
    redirect_to root_path unless current_user && current_user.admin?
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_lotion
      @lotion = Lotion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lotion_params
      params.require(:lotion).permit(:name, :description, :image1, :image2, :hotel_ids => [])
    end
end

app/views/lotions/_form.html.haml
- if @lotion.errors.present?
  = @lotion.errors.full_messages.join("<br />").html_safe
= form_for @lotion, :html => { :class => 'form-horizontal form-model' } do |f|
  .form-group
    = f.label :name, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, :class => 'text-field form-control', autocomplete: "off"
  .form-group
    = f.label :description, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_area :description, :class => 'text-area form-control', autocomplete: "off"
  .form-group
    = f.label :image1, :class => 'control-label col-md-2'
    = image_tag @lotion.image1.url(:tiny), class: "image" if @lotion.image1.present?
    .col-md-10
      = f.file_field :image1
  .form-group
    = f.label :image2, :class => 'control-label col-md-2'
    = image_tag @lotion.image2.url(:tiny), class: "image" if @lotion.image2.present?
    .col-md-10
      = f.file_field :image2
  .form-group
    = f.label :hotels, :class => 'control-label col-md-2'
    .col-md-10
      =# collection_check_boxes(:lotion, :hotel_ids, Hotel.all, :id, :name)
      = collection_select(:lotion, :hotel_ids, Hotel.all, :id, :name, {}, multiple: true, class: 'chosen', style: "min-width: '200px';")
      =# f.select_tag 'lotion[hotel_ids]', options_from_collection_for_select(Hotel.all, "id", "name"), multiple: true, class: 'chosen chosen-select'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        lotions_path, :class => 'btn btn-default'



:javascript
  $(document).ready(function(){
    //$("select[name='lotion[hotel_ids]']").chosen();
    $(".chosen").chosen();
  });

app/views/lotions/_list.html.haml
-# http://www.responsivewebmobile.com/posts/view/2013/06/04/5/Responsive_Pin_Page_templates_free

- model_class = Lotion
- item_width = local_assigns[:item_width] || 270

#lotions
  - lotions.each do |lotion|
    .masonry-item.masonry-brick{ style: "width: #{item_width}px;" }
      - if local_assigns[:show_name]
        %h5.text-center
          - truncated_name = truncate(lotion.name, length: 40, omission: "", separator: " ")
          = link_to(truncated_name, lotion_url(lotion))
      .picture
        %a.image{:href => lotion_url(lotion), :title => "Title"}
          = image_tag lotion.image1.url(:medium)
          -#%img{:alt => "", :src => lotion.image_url}/
      = rating_for lotion, "overall", enable_half: true, :half_show => true
      - if local_assigns[:show_description]
        .lotion-content
          .description
            %p=""
          .meta
            %span.price
              -#%i.icon-calendar
              =# money_format(lotion.price)
            %span
              -#%i.icon-user
              -#%a.btn.btn-green-with-white{href: lotion.affiliate_url, style: "float: right;", target: "_blank"} View Lotions
            -#%span
            -#  %i.icon-heart-empty
            -#  10
      - if local_assigns[:show_hotels]
        .meta
          %span
            = render partial: "hotels/list", locals: {hotels: lotion.hotels, item_width: 60, :hide_crud => true}
      - if current_user.present? && (current_user.admin? || lotion.created_by == current_user || current_user.superuser?)
        .meta
          %span
            - if (lotion.created_by == current_user) || current_user.superuser?
              = link_to "Edit", edit_lotion_path(lotion)#, {:class => "btn btn-primary"}
              = link_to t('.destroy', :default => t("helpers.links.destroy")),
                    lotion_path(lotion),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }

:javascript
  var $container = $('#lotions');
      $container.imagesLoaded(function(){
      $container.masonry({
        lotionSelector : '.lotion',
        columnWidth : 290,
        isAnimated: true
      });
    });

app/views/lotions/edit.html.haml
- model_class = Lotion
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Lotion
  %img{ src: "#{@lotion.image_url}", style: "display: block; width: 100%; max-width: 140px;" }
= render :partial => 'form'

app/views/lotions/index.html.haml
-# http://www.responsivewebmobile.com/posts/view/2013/06/04/5/Responsive_Pin_Page_templates_free

- model_class = Lotion

= render partial: "list", :locals => {:lotions => @lotions, :show_name => true, :show_hotels => true}

:javascript
  var $container = $('#lotions');
      $container.imagesLoaded(function(){
      $container.masonry({
        lotionSelector : '.lotion',
        columnWidth : 290,
        isAnimated: true
      });
    });

app/views/lotions/new.html.haml
- model_class = Lotion
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Add New %{model}'], :model => Lotion
  %img{ src: "#{@lotion.image_url}", style: "display: block; width: 100%; max-width: 140px;" }
= render :partial => 'form'

app/views/lotions/show.html.haml
- model_class = Lotion
.page-header
  %h1
    ="#{@lotion.name}"
  = image_tag @lotion.image1.url(:medium) if @lotion.image1.present?
  = image_tag @lotion.image2.url(:medium) if @lotion.image2.present?
  %h4= @lotion.description
  %h3 Available at these hotels
= render partial: "hotels/list", :locals => {:hotels => @lotion.hotels, :item_width => 135}

.form-group
  = link_to t('.back', :default => t("helpers.links.back")), |
    lotions_path, :class => 'btn btn-success'                  |
  - if user_signed_in? && (current_user == @lotion.created_by || current_user.superuser?)
    = link_to t('.edit', :default => t("helpers.links.edit")), |
      edit_lotion_path(@lotion), :class => 'btn btn-primary'       |
    -#
    = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
      lotion_path(@lotion),                                                                                            |
      :method => 'delete',                                                                                         |
      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
      :class => 'btn btn-danger'                                                                                   |