config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  mount Attachinary::Engine => "/attachinary"

  resources :hotels do
    member do
      get "vote"
    end
  end
  resources :lotions do
    member do
      get "vote"
    end
  end

  resources :users

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'lotions#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  has_and_belongs_to_many :lotions
  validates_presence_of :name

  has_attachment :old_logo

  has_attached_file :logo, :styles => { :tiny => "100x100>", :small => "150x150>", :medium => "400x300>", :large => "800x600>"}
  validates :logo, presence: true
  validates_attachment :logo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  belongs_to :created_by, class_name: "User"
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_filter :redirect_unless_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_hotel, only: [:show, :edit, :update, :destroy, :vote]

  # GET /hotels
  # GET /hotels.json
  def index
    # TODO: replace sort_order with acts_as_votable
    @hotels = Hotel.all

    respond_to do |format|
      format.html
      format.json { render json: @hotels }
    end

  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.created_by = current_user

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @hotel.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end

  private ##################################################################################################################################

  # TODO: use declarative_authorization gem when roles/CRUD gets more complex
  def redirect_unless_admin
    redirect_to root_path unless current_user && current_user.admin?
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :logo, :lotion_ids => [])
    end
end

app/views/hotels/_form.html.haml
- if @hotel.errors.present?
  = @hotel.errors.full_messages.join("<br />").html_safe
= form_for @hotel, :html => { :class => 'form-horizontal form-model' } do |f|
  .form-group
    = f.label :name, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, :class => 'text-field form-control', autocomplete: "off"
  .form-group
    = f.label :logo, :class => 'control-label col-md-2'
    = image_tag @hotel.logo.url(:tiny), class: "image" if @hotel.logo.present?
    .col-md-10
      = f.file_field :logo
      =# f.text_field :logo_url, :class => 'text-field form-control', autocomplete: "off"
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        hotels_path, :class => 'btn btn-default'                      |

:javascript
  $(document).ready(function(){
    $('.attachinary-input').attachinary();
  });

app/views/hotels/_list.html.haml
-# http://www.responsivewebmobile.com/posts/view/2013/06/04/5/Responsive_Pin_Page_templates_free

- model_class = Hotel
- item_width = local_assigns[:item_width] || 270

#hotels
  - hotels.each do |hotel|
    .masonry-item.masonry-brick{ style: "width: #{item_width}px;" }
      - if local_assigns[:show_name]
        %h5.text-center
          - truncated_name = truncate(hotel.name, length: 40, omission: "", separator: " ")
          = link_to(truncated_name, hotel_url(hotel))
      .picture
        %a.image{:href => hotel_url(hotel), :title => "Title"}
          = image_tag hotel.logo.url(:medium)

        - if !local_assigns[:hide_crud] && (current_user.present? && (current_user.admin? || hotel.created_by == current_user || current_user.superuser?))
          .meta
            %span
              - if current_user.admin?
                = link_to "Info", hotel_path(hotel)#, {:class => "btn btn-default"}
              - if (hotel.created_by == current_user) || current_user.superuser?
                = link_to "Edit", edit_hotel_path(hotel)#, {:class => "btn btn-primary"}
                = link_to t('.destroy', :default => t("helpers.links.destroy")),
                      hotel_path(hotel),
                      :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }

:javascript
  var $container = $('#hotels');
      $container.imagesLoaded(function(){
      $container.masonry({
        hotelSelector : '.hotel',
        columnWidth : 290,
        isAnimated: true
      });
    });

app/views/hotels/edit.html.haml
- model_class = Hotel
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Hotel
  %img{ src: "#{@hotel.logo_url}", style: "display: block; width: 100%; max-width: 140px;" }
= render :partial => 'form'

app/views/hotels/index.html.haml
-# TODO: Scrape this site? https://www.goavm.com/hotel-brand-products-c-469.aspx
= render partial: "list", :locals => {:hotels => @hotels}

app/views/hotels/new.html.haml
- model_class = Hotel
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Add New %{model}'], :model => Hotel
  %img{ src: "#{@hotel.logo_url}", style: "display: block; width: 100%; max-width: 140px;" }
= render :partial => 'form'

app/views/hotels/show.html.haml
- model_class = Hotel
.page-header
  %h1
    Hotel Info
  = image_tag @hotel.logo.url(:medium)

  %h3 Lotions at this Hotel
  = render partial: "lotions/list", :locals => {:lotions => @hotel.lotions}

.form-group
  = link_to t('.back', :default => t("helpers.links.back")), |
    hotels_path, :class => 'btn btn-success'                  |
  - if user_signed_in? && (current_user == @hotel.created_by || current_user.superuser?)
    = link_to t('.edit', :default => t("helpers.links.edit")), |
      edit_hotel_path(@hotel), :class => 'btn btn-primary'       |
    -#
    = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
      hotel_path(@hotel),                                                                                            |
      :method => 'delete',                                                                                         |
      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
      :class => 'btn btn-danger'                                                                                   |